[build]
builder = "nixpacks"
buildCommand = "cd backend && npm run start"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[nixpacks]
node_version = "18"